### ISSUE TITLE
Update the Kudos Carnival Menu

### ISSUE THREAD

**Issue by ndkazu** [kudos-ink/portal#121]
In Order to make it easier for participants to find new issues, the Kudos Carnival menu could/should disable issues with **active** PRs.
The latest status on the issues that might  is as follows:

- [x]  Polkadot(Refactor pallets to V2 bench syntax) => in work but several items included:(Kazu, Ludovic, etc...)
- [x]   OpenZeppelin(Clean code comments in macro expansion (from templates)) => in work: Parth  
- [x]   Polkadot(polkadot-sdk-docs: Use command_macro!) => in work: Kazu
- [x]   Polkadot(Idea: polkadot-dev CLI) => in work: Parth
- [x]   PlutoWallet(Address registry) => in work: Parth

**Comment by ipapandinas** [comment]
Hey @ndkazu - thank you for sharing this, I've just updated the leaderboard
You're leading for now, kudos! 🏆
